# -*- coding: utf-8 -*-
"""MQTT_client

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15FRw-whK7GcbV9Pv1v6uXkZkyhtJbT-y
"""

pip install paho-mqtt

import paho.mqtt.client as mqtt
import time


def decode(input_string):
    rssi_hex = input_string[:8]  # First 8 characters for RSSI in hexadecimal
    snr_hex = input_string[8:16]  # Next 8 characters for SNR in hexadecimal
    message_hex = input_string[16:]  # Rest of the characters for the message in hexadecimal

    # Convert hexadecimal strings to integers
    rssi = int(rssi_hex, 16) - 0x100000000
    snr = int(snr_hex, 16)/10

    # Convert the remaining hexadecimal part to ASCII to get the message
    message_ascii = bytes.fromhex(message_hex).decode('utf-8')

    return rssi, snr, message_ascii

def on_message(client, userdata, message):
    global recibido
    recibido = True
    print("Message received: " + str(message.payload.decode("utf8")))
    print("Topic" + str(message.topic))
    rssi, snr, msn = decode(message.payload.decode("utf8"))
    print("RSSI: " + str(rssi))
    print("SNR: " + str(snr))
    print("Message: " + str(msn))

def on_connect(client, userdata, flags, rc):
    if rc ==0:
          global connected
          if connected == False:
            print("Connected OK")
            connected = True

connected = False
recibido = False

broker_address = "test.mosquitto.org"
port = 1883

client = mqtt.Client("asdasad")
client.connect(broker_address, port = port)

client.loop_start()
client.subscribe("dragino-2277dc/E66118C4/data")
client.on_message = on_message

while recibido!= True:
  time.sleep(20)

client.loop_stop()